apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pocketbase-helm.fullname" . }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ include "pocketbase-helm.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "pocketbase-helm.fullname" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/pocketbase/pocketbase"]
          args: ["serve", "--http=0.0.0.0:8090", "--encryptionEnv=PB_ENCRYPTION_KEY"]
          {{- if .Values.flags.encryptionEnv }}
          env:
            - name: PB_ENCRYPTION_KEY
              value: {{ .Values.flags.encryptionEnv | quote }}
          {{- end }}
          ports:
            - name: http
              containerPort: 8090
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /pocketbase/pb_data
              name: {{ include "pocketbase-helm.fullname" . }}-pv
      volumes:
        - name: {{ include "pocketbase-helm.fullname" . }}-pv
          persistentVolumeClaim:
            claimName: {{ include "pocketbase-helm.fullname" . }}-pvc