apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "pocketbase-helm.fullname" . }}-pvc
spec:
  {{if .Values.persistence.storageClass}}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{end}}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.storage }}