apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "pocketbase-helm.fullname" . }}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.storage }}