apiVersion: v1
kind: Service
metadata:
  name: {{ include "pocketbase-helm.fullname" . }}
spec:
  selector:
    app: {{ include "pocketbase-helm.fullname" . }}
  type: ClusterIP
  ports:
    - port: 8090
      targetPort: 8090
      protocol: TCP
      name: pocketbase-port
