## @section PocketBase configuration
##

## @param replicaCount How many replicas of pocketbase should be deployed, it is ignored if autoscaling is enabled
## @param nameOverride String to partially override the deployment name (will maintain the release name)
## @param fullnameOverride String to fully override the deployment name
##
replicaCount: 1
nameOverride: ""
fullnameOverride: pocketbase

## @param flags.encryptionEnv The PB_ENCRYPTION_KEY 32 characters string, see https://pocketbase.io/docs/going-to-production/#:~:text=enable%20settings%20encryption for more infos
##
flags:
  encryptionEnv: ""


## @param image.repository The repository (and image name) where the pocketbase docker image is stored
## @param image.pullPolicy Deployment pull policy
## @param image.tag Overrides the image tag whose default is the chart appVersion
##
image:
  repository: rg.fr-par.scw.cloud/sepropriodev/pocketbase
  pullPolicy: IfNotPresent
  tag: ""

## @param persistence.storage How much storage space should be reserved for PocketBase
## @param persistence.storageClass The PV storage class (a storageClass with Retain policy is recommended)
##
persistence:
  storage: 2Gi
  storageClass: ""

## @param service.type The service type exposing the PocketBase pods
## @param service.port The port on which PocketBase is exposed
##
service:
  type: ClusterIP
  port: 8090

## @param resources The resources associated with the deployment
resources: {}

## @param autoscaling.enabled Whether to enable autoscaling
## @param autoscaling.minReplicas number of min replicas
## @param autoscaling.maxReplicas number of max replicas
## @param autoscaling.targetCPUUtilizationPercentage targetCPUUtilizationPercentage
## @param autoscaling.targetMemoryUtilizationPercentage targetMemoryUtilizationPercentage
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
